---
#    2  git clone --single-branch --branch v1.7.2 https://github.com/rook/rook.git
- name: Clone rook repo
  git:
    repo: https://github.com/rook/rook.git
    dest: /home/vagrant
    version: v1.7.2
#    3  cd rook/cluster/examples/kubernetes/ceph/
#    4  kubectl create -f crds.yaml -f common.yaml -f operator.yaml
- name: Create ceph cluster
  command: kubectl create -f /home/vagrant/rook/cluster/examples/kubernetes/ceph/crds.yaml -f /home/vagrant/rook/cluster/examples/kubernetes/ceph/common.yaml -f /home/vagrant/rook/cluster/examples/kubernetes/ceph/operator.yaml


#    5  kubectl create -f cluster.yaml
- name: Create ceph cluster
  command: kubectl create -f /home/vagrant/rook/cluster/examples/kubernetes/ceph/cluster.yaml

# TODO: wait until all up and running
#   85  kubectl create -f kubectl create -f cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
#   86  kubectl create -f cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
#       kubectl create -f cluster/examples/mysql.yaml
#       kubectl create -f cluster/examples/wordpress.yaml
#       https://github.com/rook/rook/blob/master/Documentation/direct-tools.md#block-storage-tools
